import tornado.ioloop
import tornado.web
import os

"""
Redirects were generated by this hack script
convert wp pages to new jekyll urls
------------
import glob

print "{"
for post in glob.glob('_posts/*.markdown'):
    parts = post.split('-')
    dir = '/'.join(parts[:3]).replace('_posts/','')
    file = '-'.join(parts[3:]).replace('.markdown','')
    url = "/%s/%s/" % (dir, file)
    with open(post, 'r') as fh:
        for line in fh.readlines():
            if line.startswith('wpid'):
                wpid = int(line.replace('wpid:','').replace("'", '').strip())
    old = "/wordpress/?p=%d" % wpid
         
    print "'%d': '%s'," % (wpid, url)

print "}"
"""

redirects = {
    '76': 'http://blog.perrygeo.net/2007/09/04/performance-testing-rasters-with-mapserver/',
    '116': 'http://blog.perrygeo.net/2008/04/19/a-quick-cython-introduction/',
    '130': 'http://blog.perrygeo.net/2009/02/12/stimulus-watch/',
    '123': 'http://blog.perrygeo.net/2008/05/28/geospatial-reddit-a-democratic-solution-to-geo-blog-overload/',
    '54': 'http://blog.perrygeo.net/2006/06/25/mapserver-include/',
    '58': 'http://blog.perrygeo.net/2007/05/13/back-on-the-train/',
    '67': 'http://blog.perrygeo.net/2007/05/14/blessed-unrest-paul-hawkens-presentation/',
    '39': 'http://blog.perrygeo.net/2006/04/11/animating-static-maps-the-geologic-evolution-of-north-america/',
    '27': 'http://blog.perrygeo.net/2006/02/04/first-thoughts-on-the-open-source-geospatial-foundation/',
    '126': 'http://blog.perrygeo.net/2008/06/12/geospatial-reddit-2-weeks-later/',
    '77': 'http://blog.perrygeo.net/2007/09/04/mapserver-vs-mapnik-revisited/',
    '83': 'http://blog.perrygeo.net/2007/09/25/autodesk-open-sources-coordinate-system-software/',
    '10': 'http://blog.perrygeo.net/2007/10/20/turning-ubuntu-into-a-gis-workstation/',
    '163': 'http://blog.perrygeo.net/2012/03/25/working-with-mbtiles-in-python/',
    '89': 'http://blog.perrygeo.net/2007/10/20/poetics-of-cartography/',
    '111': 'http://blog.perrygeo.net/2008/04/02/working-hard-for-some-rest/',
    '70': 'http://blog.perrygeo.net/2007/06/10/ogr-and-matplotlib-examples/',
    '60': 'http://blog.perrygeo.net/2007/05/28/qgis-geocoding-plugin/',
    '2': 'http://blog.perrygeo.net/2005/12/03/the-new-blog/',
    '86': 'http://blog.perrygeo.net/2007/10/12/ctech-software-goes-multithreaded/',
    '140': 'http://blog.perrygeo.net/2009/12/16/peaksware-licensing-revisted/',
    '7': 'http://blog.perrygeo.net/2006/02/08/gdal-based-dem-utilities/',
    '71': 'http://blog.perrygeo.net/2007/06/11/desktop-vs-web-ui/',
    '105': 'http://blog.perrygeo.net/2008/02/02/why-is-the-command-line-a-dying-art/',
    '142': 'http://blog.perrygeo.net/2010/03/31/distributed/',
    '38': 'http://blog.perrygeo.net/2006/04/01/lidar-data-processing-with-python-and-ogr/',
    '107': 'http://blog.perrygeo.net/2008/02/17/google-earth-and-the-tilt-sensor-joystick-on-the-x61s/',
    '50': 'http://blog.perrygeo.net/2006/05/18/more-on-mapnik-wms/',
    '91': 'http://blog.perrygeo.net/2007/11/12/looking-for-lidar-services/',
    '3': 'http://blog.perrygeo.net/2005/12/11/kml-to-shapefile-scripting/',
    '96': 'http://blog.perrygeo.net/2007/12/06/google-charts-their-latest-web-service/',
    '82': 'http://blog.perrygeo.net/2007/09/18/parallel-python-and-gis/',
    '139': 'http://blog.perrygeo.net/2009/08/10/nice-examples-of-esris-geoprocessing-python-module-93/',
    '131': 'http://blog.perrygeo.net/2009/02/19/tv-cycling-coverage-is-dead/',
    '141': 'http://blog.perrygeo.net/2010/02/18/lazy-raster-processing-with-gdal-vrts/',
    '55': 'http://blog.perrygeo.net/2006/07/03/wardriving-with-ubuntu-linux-and-google-earth/',
    '108': 'http://blog.perrygeo.net/2008/02/15/human-impacts-on-the-global-marine-ecosystem/',
    '5': 'http://blog.perrygeo.net/2006/01/20/geocoding-an-address-list-to-shapefile/',
    '59': 'http://blog.perrygeo.net/2007/05/13/worldwind-java-jython-example/',
    '160': 'http://blog.perrygeo.net/2012/02/24/utfgrids-with-openlayers-and-tilestache/',
    '88': 'http://blog.perrygeo.net/2007/10/19/update-to-qgis-geocoding-plugin/',
    '151': 'http://blog.perrygeo.net/2010/12/20/um-nice-review-of-qgis/',
    '47': 'http://blog.perrygeo.net/2006/05/06/the-impact-of-urban-areas-on-co2-emmissions/',
    '132': 'http://blog.perrygeo.net/2009/03/25/the-magic-bullet/',
    '57': 'http://blog.perrygeo.net/2006/07/24/the-reliability-of-web-services/',
    '162': 'http://blog.perrygeo.net/2012/03/18/average-aspect/',
    '48': 'http://blog.perrygeo.net/2006/05/12/educational-ways-to-waste-some-time/',
    '74': 'http://blog.perrygeo.net/2007/08/03/zaca-lake-fire-map/',
    '119': 'http://blog.perrygeo.net/2008/05/14/ubuntu-as-a-gis-workstation-updated-for-hardy-heron/',
    '79': 'http://blog.perrygeo.net/2008/01/06/mirone-a-gui-for-gdal-and-gmt/',
    '13': 'http://blog.perrygeo.net/2007/05/27/python-gpsd-bindings/',
    '25': 'http://blog.perrygeo.net/2006/01/24/mexico-us-border-crossing-maps/',
    '45': 'http://blog.perrygeo.net/2006/05/05/usgs-seamless-is-back/',
    '106': 'http://blog.perrygeo.net/2008/02/16/the-shiny-new-x61s/',
    '135': 'http://blog.perrygeo.net/2009/06/16/ironpython-and-arcgis-not-quite-ready-for-prime-time/',
    '66': 'http://blog.perrygeo.net/2007/05/14/cleaning-up-cad-data-with-postgis/',
    '104': 'http://blog.perrygeo.net/2008/01/26/impervious-surface-deliniation-with-grass/',
    '149': 'http://blog.perrygeo.net/2010/06/09/kmltree/',
    '134': 'http://blog.perrygeo.net/2009/06/12/the-gps-told-me-to-do-it/',
    '125': 'http://blog.perrygeo.net/2008/06/08/jabref-open-source-alternative-to-endnote/',
    '143': 'http://blog.perrygeo.net/2010/05/06/exploring-geometry/',
    '52': 'http://blog.perrygeo.net/2006/06/09/animating-the-blue-marble/',
    '56': 'http://blog.perrygeo.net/2006/07/14/converting-shapefiles-and-more-to-kml/',
    '98': 'http://blog.perrygeo.net/2007/12/12/geologist-vs-engineer/',
    '137': 'http://blog.perrygeo.net/2009/06/21/reading-xfs-partition-from-windows/',
    '136': 'http://blog.perrygeo.net/2009/06/16/ironpython-26-and-arcgis-ready-for-prime-time/',
    '152': 'http://blog.perrygeo.net/2011/05/18/optimizing-kml-for-hierarchical-polygon-data/',
    '64': 'http://blog.perrygeo.net/2007/05/19/sparklines-in-python/',
    '43': 'http://blog.perrygeo.net/2006/04/25/whats-going-on-with-seamlessusgsgov/',
    '29': 'http://blog.perrygeo.net/2006/02/13/forest-service-plans-largest-land-sale-in-decades/',
    '148': 'http://blog.perrygeo.net/2010/05/27/marinemap-wins-award-for-environmental-conflict-resolution/',
    '122': 'http://blog.perrygeo.net/2008/05/25/so-you-want-to-learn-to-learn-about-kriging/',
    '128': 'http://blog.perrygeo.net/2008/07/15/r-is-for-radiohead/',
    '93': 'http://blog.perrygeo.net/2007/11/20/privacy-location-technology-and-bad-journalism/',
    '35': 'http://blog.perrygeo.net/2006/03/26/wms-layers-my-top-ten/',
    '112': 'http://blog.perrygeo.net/2008/04/11/shell-history-why-not/',
    '4': 'http://blog.perrygeo.net/2005/12/11/tissot-indicatrix-examining-the-distortion-of-2d-maps/',
    '78': 'http://blog.perrygeo.net/2007/09/05/the-world-turned-right-side-up/',
    '49': 'http://blog.perrygeo.net/2006/05/17/mapnik-wms-server/',
    '124': 'http://blog.perrygeo.net/2008/05/28/posting-to-geospatial-reddit/',
    '42': 'http://blog.perrygeo.net/2006/04/23/the-distinction-between-open-source-and-open-standards/',
    '68': 'http://blog.perrygeo.net/2007/05/31/fdo-gdalogr-and-fme/',
    '30': 'http://blog.perrygeo.net/2006/02/17/starspan-for-vector-on-raster-analysis/',
    '99': 'http://blog.perrygeo.net/2007/12/19/more-on-google-charts-and-a-python-interface/',
    '97': 'http://blog.perrygeo.net/2007/12/10/quick-way-to-publish-a-point-shapefile-to-web/',
    '114': 'http://blog.perrygeo.net/2008/04/21/hike-of-doom-2-ogc-kml/',
    '95': 'http://blog.perrygeo.net/2007/12/05/take-the-larger-view-of-gis/',
    '115': 'http://blog.perrygeo.net/2008/04/15/spatial-data-in-sqlite/',
    '75': 'http://blog.perrygeo.net/2007/08/28/mapping-the-undesirable/',
    '1': 'http://blog.perrygeo.net/2005/12/03/hello-world/',
    '94': 'http://blog.perrygeo.net/2007/12/04/for-the-cartographers-in-the-house/',
    '138': 'http://blog.perrygeo.net/2009/06/23/peaksware-licensing-hell/',
    '110': 'http://blog.perrygeo.net/2008/03/12/upcoming-books/',
    '53': 'http://blog.perrygeo.net/2006/06/15/some-thoughts-on-where-20/',
    '51': 'http://blog.perrygeo.net/2006/06/03/hostgis-linux-36-released/',
}

class MainHandler(tornado.web.RequestHandler):
    def initialize(self):
        pass

    def get(self):
        page = self.get_arguments('p')
        try:
            page = page[0]
            self.redirect(redirects[page], permanent=True)
        except IndexError:
            pass

        feed = self.get_arguments('feed')
        try:
            feed = feed[0]
            self.redirect('http://blog.perrygeo.net/atom.xml', permanent=True)
        except IndexError:
            self.redirect('http://blog.perrygeo.net/', permanent=True)
 

if __name__ == "__main__":
    urls = [
        ( r'/wordpress/', MainHandler, )
    ]
    application = tornado.web.Application(urls, debug=True)
    application.listen(8988)
    tornado.ioloop.IOLoop.instance().start()
